app:
  dataSource:
    postgres:
      port: 5433
      username: postgres
      password: infobipsifra
      host: localhost
      databaseName: test
      jdbc-url: jdbc:postgresql://${app.dataSource.postgres.host}:${app.dataSource.postgres.port}/${app.dataSource.postgres.databaseName}